[package]
name = "PolymediaProfile"
version = "0.0.1"
authors = ["juzybits <https://twitter.com/juzybits>"]

[dependencies]
Sui = { local = "../../sui/crates/sui-framework" }

[addresses]
polymedia_profile = "0xf8766e02ae349b9e3021bf09e3cc361641961c8d"
